console.log('aaaaaa')
console.log('bbbbbb')
console.log('cccccc')
setTimeout(() => {console.log('dddddd')}, 5000)
console.log('eeeeee')
console.log('ffffff')
fetch('http://localhost:3000/').then(res => res.json()).then(data => console.log(data))